### ISSUE TITLE
Failed to run the example tests due to .NET incompatibility with openSSL on coreOS

### ISSUE THREAD

**Issue by alexanderst** [hypar-io/CppWrapperExample#1]
I cloned this example today, created docker image and built C++ and C# parts. I have a failure running the test. Investigated it with LD_DEBUG="libs" and the problem is that libsso.so is incompatible between dotnet and coreOS in docker image. 
Please advice if this problem can be resolved somehow locally. I can provide complete log if needed. I have an idea that dotnet 5.0 installation will help, but it's incompatible with hypar service, so I will not be able to publish the function. 

```bash-4.2# dotnet test
Test run for /function/test/bin/Debug/netcoreapp3.1/CppWrapperExample.Tests.dll(.NETCoreApp,Version=v3.1)
Microsoft (R) Test Execution Command Line Tool Version 16.7.1
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
[xUnit.net 00:00:01.13]     CppWrapperExample.Tests.WrapperTests.CallsWrapperMethodSuccessfully [FAIL]
  X CppWrapperExample.Tests.WrapperTests.CallsWrapperMethodSuccessfully [6ms]
  Error Message:
   System.DllNotFoundException : Unable to load shared library 'libhello-cpp.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibhello-cpp.so: cannot open shared object file: No such file or directory
  Stack Trace:
     at CppWrapperExample.CppWrapperExample.TheSecretOfTheUniverse()
   at CppWrapperExample.CppWrapperExample.Execute(Dictionary`2 inputModels, CppWrapperExampleInputs input) in /function/src/CppWrapperExample.cs:line 25
   at CppWrapperExample.Tests.WrapperTests.CallsWrapperMethodSuccessfully() in /function/test/WrapperTests.cs:line 11

Test Run Failed.```

**Comment by alexanderst** [comment]
I've managed to build the project (copying libhello-cpp.so should be done during .sln loading, but it failed for me, so I had to do this manually). So "dotnet test" was successful, then I did "hypar publish". The function was not loaded on Hypar:
```Unable to load shared library 'libhello-cpp.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibhello-cpp.so: cannot open shared object file: No such file or directory```

**Comment by ikeough** [comment]
@alexanderst Can you give me an idea of the type of system that you are building on? We've built on both macs and PCs and haven't had a problem with an outdated version of OpenSSL as mentioned in your Discord post.

**Comment by ikeough** [comment]
I've just tested the Amazon Linux 2 docker container and it seems that OpenSSL isn't installed at all. So is the problem "libsso.so is incompatible between dotnet and coreOS" that you bundled a version of openssl that is compatible with .net core but it's being rejected by the Amazon Linux 2 environment?

**Comment by ikeough** [comment]
For reference (not sure that it's related): https://forums.aws.amazon.com/thread.jspa?threadID=244810

**Comment by alexanderst** [comment]
@ikeough Yes, it looks like my case. AWS environment has openSSL 1.0.0. Dotnet requires OpenSSL 1.1.1.  I'm using Amazon Linux 2 Docker container. If I install higher version of OpenSSL in this image - it works. It doesn't work on AWS even when I publish openSSL 1.1.1 with my .so files.
The only environment which worked smoothly was Ubuntu 20 and dotnet 3.1. Ubuntu 18 didn't work either.

**Comment by ikeough** [comment]
We've just tested this on another setup with Windows (I had previously created the function on a Mac), and the example built, published, and ran on Hypar without an issue. It could be that something about the code that you are testing is causing that dependency to be excercised when it is not with our very simple example. It's hard for us to debug without a minimal test case that reproduces the problem.

**Comment by ikeough** [comment]
Thinking that perhaps it was code that you have which might be requiring OpenSSL, I added the following lines to the function:
```csharp
using System.Security.Cryptography;
...
var rsa = new RSAOpenSsl();
```
And I added the `System.Security.Cryptography.OpenSSL` nuget package. The function built, deployed, and ran without a problem, suggesting that it is using the correct version of OpenSSL.

**Comment by ikeough** [comment]
Re-reading the start of this post, I suspected that I could recreate this simply by running the tests. But running the tests from inside the container was successful as well:
```
bash-4.2# dotnet test
Test run for /function/test/bin/Debug/netcoreapp3.1/CppWrapperExample.Tests.dll(.NETCoreApp,Version=v3.1)
Microsoft (R) Test Execution Command Line Tool Version 16.7.1
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
Hello Hypar from C++!

Test Run Successful.
Total tests: 1
     Passed: 1
 Total time: 2.9434 Seconds
bash-4.2# 
```

@alexanderst Where are you seeing an error related to compatibility with OpenSSL?

**Comment by alexanderst** [comment]
I've created minimal example with openSSL error. The idea is to add openSSL dependency to C++ part of CppWrapperExample. Then I copied libssl.so 1.1.1 to "publish" folder and run "dotnet test" on docker container. In LD_DEBUG log I see that  error is caused by dotnet calling the system libssl.so of 1.0 version:
calling init: /usr/share/dotnet/shared/Microsoft.NETCore.App/3.1.13/System.Security.Cryptography.Native.OpenSsl.so
...
/lib64/libssl.so.10: error: symbol lookup error: undefined symbol: DSA_get0_key (fatal)

If I install libssl.so 1.1.1 manually in container - it works. Then I tried make it work on default image. Copied libssl.so.1.1.1 to publish folder and set LD_LIBRARY_PATH to load it in the first turn. The error reproduced again - looks like all transient dependencies should be considered.

**Comment by ikeough** [comment]
I can recreate the problem that you've experienced. Unfortunately, there's no great answer without building a custom lambda runtime that has a specific version of openssl installed so that we can get this to work. We'd like to support this in the future, but currently don't have the bandwidth to support this request. 

Can I ask what the requirement is for OpenSSL in the function code? Perhaps there's a way to work around the issue.

**Comment by alexanderst** [comment]
OpenSSL is a transient dependency. I'll try to find workaround, though not sure if it's possible. 
Thank you for your help!
